// 'use client';
import './globals.css'
import { Mulish } from 'next/font/google'
// import { AuthContextProvider } from '@/context/AuthContext'
// @ts-ignore
import { Header } from "@/app/components/index";
import {getServerSession} from "next-auth";
import {authOptions} from "@/utils/authOptions";
import SessionProvider from "./SessionProvider";

const inter = Mulish({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
    const session = await getServerSession(authOptions);
  return (
      <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
      <Header />

      {children}
      </SessionProvider>
      </body>
      </html>
  )
}
